name: Build macOS App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      CI: true
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        brew update
        brew install clang-format cmake llvm glfw glew pkg-config
    
    - name: Build
      run: |
        ./build.sh
        
    - name: Package
      run: |
        ./pack.sh
        mv Ned.dmg Ned-macOS-$(git rev-parse --short HEAD).dmg
        
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: Ned-macOS
        path: Ned-macOS-*.dmg
