name: Multi-Platform Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos-arm:
    runs-on: macos-14
    permissions:
      contents: write  # Required for releases
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install dependencies
        run: brew install clang-format cmake llvm glfw glew pkg-config
      
      - name: Build
        run: ./build.sh
      
      - name: Package
        run: |
          ./pack-mac.sh
          SHORT_SHA=$(git rev-parse --short HEAD)
          mv Ned.zip "Ned-macOS-ARM64-${SHORT_SHA}.zip"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
      
      - name: Upload ARM Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-macOS-ARM64-*.zip
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "Build ${{ env.SHORT_SHA }}"
          generate_release_notes: true
          draft: false
          prerelease: false

  macos-intel:
    runs-on: macos-13  # Updated to supported runner
    permissions:
      contents: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: brew install clang-format cmake llvm glfw glew pkg-config
      
      - name: Build
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.15
          ./build.sh
      
      - name: Package
        run: |
          ./pack-mac.sh
          SHORT_SHA=$(git rev-parse --short HEAD)
          mv Ned.zip "Ned-macOS-Intel-${SHORT_SHA}.zip"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV  # Add this line
      
      - name: Upload Intel Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-macOS-Intel-*.zip
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "Build ${{ env.SHORT_SHA }}"
          draft: false
          prerelease: false

  debian:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libglfw3-dev libglew-dev libgtk-3-dev pkg-config build-essential libcurl4-openssl-dev clang-format mesa-utils
      
      - name: Build
        run: ./build.sh
            
      - name: Package
        run: |
          sudo chmod +x pack-deb.sh
          ./pack-deb.sh
          SHORT_SHA=$(git rev-parse --short HEAD)
          mv Ned_*.deb "Ned-Debian-${SHORT_SHA}.deb"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          
      - name: Upload Debian Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-Debian-*.deb
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "Build ${{ env.SHORT_SHA }}"
          draft: false
          prerelease: false