name: Build macOS App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-14
    env:
      CI: true
    permissions:
      contents: write  # Allows uploading to releases

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Install dependencies
        run: |
          brew install clang-format cmake llvm glfw glew pkg-config
    
      - name: Build
        run: |
          ./build.sh
        
      - name: Package
        run: |
          ./pack.sh
          SHORT_SHA=$(git rev-parse --short HEAD)
          mv Ned.zip "Ned-macOS-${SHORT_SHA}.zip"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        
      - name: Upload ZIP to Releases
        # Only run on push to main or manual trigger (not pull requests)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          # Match the generated ZIP file name
          files: Ned-macOS-*.zip
          # Tag name with short SHA for uniqueness
          tag_name: "build-${{ env.SHORT_SHA }}"
          # Release name/title
          name: "Build (${{ env.SHORT_SHA }})"
          # Auto-generate release notes (optional)
          generate_release_notes: true
          # Ensure this is NOT a draft or pre-release
          draft: false
          prerelease: false