name: Multi-Platform Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Common environment variables for all jobs
env:
  RELEASE_TAG: "v$(date -u +'%Y.%m.%d.%H%M%S')"  # Year.Month.Day.HourMinuteSecond
  RELEASE_NAME: "Build $(date -u +'%Y-%m-%d %H:%M UTC')"

jobs:
  macos-arm:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Get full commit history for accurate SHAs
          
      - name: Install dependencies
        run: brew install clang-format cmake llvm glfw glew pkg-config
      
      - name: Build
        run: ./build.sh
      
      - name: Package
        run: |
          ./pack-mac.sh
          mv Ned.zip "Ned-macOS-ARM64-${RELEASE_TAG}.zip"
      
      - name: Upload ARM Release
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-macOS-ARM64-*.zip
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          generate_release_notes: true
          draft: false
          prerelease: false
          update: true  # Critical for merging uploads

  macos-intel:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: brew install clang-format cmake llvm glfw glew pkg-config
      
      - name: Build
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.15
          ./build.sh
      
      - name: Package
        run: |
          ./pack-mac.sh
          mv Ned.zip "Ned-macOS-Intel-${RELEASE_TAG}.zip"
      
      - name: Upload Intel Release
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-macOS-Intel-*.zip
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          update: true

  debian:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libglfw3-dev libglew-dev libgtk-3-dev \
            pkg-config build-essential libcurl4-openssl-dev clang-format mesa-utils
      
      - name: Build
        run: ./build.sh
      
      - name: Package
        run: |
          chmod +x pack-deb.sh
          ./pack-deb.sh
          mv Ned_*.deb "Ned-Debian-${RELEASE_TAG}.deb"
      
      - name: Upload Debian Release
        uses: softprops/action-gh-release@v1
        with:
          files: Ned-Debian-*.deb
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          update: true